---
general:
  cors:
    origins: ['http://localhost:4200']
    methods: ['GET', 'POST']
    headers: ['Origin', 'Content-Type']
dns:
   internalServers: ['8.8.4.4'] #ipv6 addresses must be enclosed in brackets []
   externalServers: ['8.8.8.8']